#!/usr/bin/env bash
# scanman-scan.sh — populate bootstrap inventory layers in an existing workspace.
#
# Modes:
#   focused              (default) — regenerate 00/00b/01/02
#   reproduction-spec    (v0.6)    — additionally enrich 00 with archetype column
#                                    (delegated to the agent; bash adds the column header)
#
# Delegates to the Rust binary when available; otherwise emits a minimal
# bootstrap and warns that full inventory generation requires the Rust impl.
#
# Usage:
#   scanman-scan.sh [--mode=MODE] <repo-path> <slug>
#   scanman-scan.sh [--mode=MODE] <workspace>   # reproduction-spec form
#   scanman-scan.sh --help

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./_scanman-lib.sh
. "${SCRIPT_DIR}/_scanman-lib.sh"

usage() {
    cat <<'EOF'
scanman-scan.sh — populate bootstrap inventory in a scanman workspace

USAGE:
  scanman-scan.sh [--mode=MODE] <repo-path> <slug>
  scanman-scan.sh [--mode=MODE] <workspace-dir>
  scanman-scan.sh --help

OPTIONS:
  --mode=MODE       focused (default) | reproduction-spec
  --help, -h        Show this help.

ARGUMENTS:
  repo-path         Path to the repo being analyzed (focused/positional form).
  slug              Workspace slug.
  workspace-dir     Existing workspace directory (reproduction-spec form).

NOTES:
  - In focused mode this regenerates 00-file-inventory.md, 00b-dependency-map.md,
    01-system-map.md, 02-runtime-model.md while preserving YAML frontmatter
    and enriched bodies (Rust impl only).
  - In reproduction-spec mode, additionally adds an `archetype` column to
    00-file-inventory.md so the agent can classify each source file.
  - The Rust impl is the canonical source. The bash fallback creates a
    skeleton if the Rust binary is unavailable, plus a hint to install/build.

ENV:
  SCANMAN_MODE          Default mode when --mode= not supplied.
  AGENTBRAIN_DIR        Override vault root (default: $HOME/agentBrain).
EOF
}

# --- helpers (defined before main logic) ---------------------------------------

enrich_inventory_archetype() {
    local ws="$1"
    local inv="$ws/00-file-inventory.md"
    [ -f "$inv" ] || return 0
    if grep -q "Archetype classification" "$inv"; then
        return 0
    fi
    info "adding 'Archetype' section to $inv (reproduction-spec mode)"
    cat >> "$inv" <<'EOF'

## Archetype classification (reproduction-spec mode)

Per source-file, assign one of:

| Archetype | Detection |
|-----------|-----------|
| data-only | `pub const X` + structs without methods/state |
| state-machine | `State = enum`, `Action = enum`, dispatch |
| host-export | `extern fn`, `export fn`, module-level `var` |
| primitive | default for mixed data+logic |

Fill in below. Each row maps a source-file from the inventory above.

| Source file | Archetype | Template |
|-------------|-----------|----------|
| [fill in] | | |
EOF
}

# --- arg parsing ---------------------------------------------------------------

for a in "$@"; do
    case "$a" in
        --help|-h) usage; exit 0 ;;
    esac
done

parse_mode_flag "$@"
ARGS=("${SCANMAN_PASSTHRU_ARGS[@]:-}")
MODE="$SCANMAN_PARSED_MODE"

if [ "${#ARGS[@]}" -eq 0 ] || [ -z "${ARGS[0]:-}" ]; then
    echo "ERROR: <repo-path> and <slug> (or <workspace-dir>) required" >&2
    echo "" >&2
    usage >&2
    exit 2
fi

# --- delegate to Rust binary when available ------------------------------------

BIN="$(detect_scanman_bin)"

if [ -n "$BIN" ] && [ "${#ARGS[@]}" -ge 2 ]; then
    REPO_PATH="${ARGS[0]}"
    SLUG="${ARGS[1]}"
    info "delegating to Rust binary: $BIN scan"
    "$BIN" scan "$REPO_PATH" "$SLUG"
    rc=$?
    if [ "$MODE" = "reproduction-spec" ] && [ "$rc" -eq 0 ]; then
        WS="$SCANMAN_AGENTBRAIN_DIR/local/research/repo-distill/$SLUG"
        enrich_inventory_archetype "$WS"
    fi
    exit $rc
fi

# --- pure-bash fallback (minimal) ----------------------------------------------

WORKSPACE=""
REPO_PATH=""
SLUG=""

if [ "${#ARGS[@]}" -ge 2 ]; then
    REPO_PATH="${ARGS[0]}"
    SLUG="${ARGS[1]}"
    WORKSPACE="$SCANMAN_AGENTBRAIN_DIR/local/research/repo-distill/$SLUG"
elif [ "${#ARGS[@]}" -eq 1 ]; then
    WORKSPACE="${ARGS[0]}"
    SLUG="$(basename "$WORKSPACE")"
fi

require_workspace "$WORKSPACE"

warn "Rust binary not available; running minimal bash bootstrap (no full inventory walk)."
warn "Install: cargo build --release in ${SCRIPT_DIR}/rust-impl"

INV="$WORKSPACE/00-file-inventory.md"
if grep -q "^# File inventory" "$INV" 2>/dev/null; then
    : # already populated
else
    info "writing inventory skeleton to $INV"
    cat >> "$INV" <<EOF

# File inventory (bash-bootstrap stub)

> Generated by scanman-scan.sh in pure-bash fallback mode. Replace this with the
> Rust impl output (\`scanman scan <repo-path> <slug>\`) for a real inventory.

| Path | Role | Status | Notes |
|------|------|--------|-------|
| [fill in] | | | |
EOF
fi

if [ "$MODE" = "reproduction-spec" ]; then
    enrich_inventory_archetype "$WORKSPACE"
fi

echo "Bootstrap complete (bash fallback): $WORKSPACE"
exit 0
