import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { BRAIN_DIR } from "../brain-paths";
import { CORE_FILES } from "./constants";
import { collectProjectContext } from "./project";
import { relativeToBrain } from "./paths";
import type { BrainStatusContext } from "./status";

export async function buildAgentBrainSystemPrompt(
	systemPrompt: string,
	ctx: BrainStatusContext,
): Promise<string> {
	const { projectDir, sections } = await collectProjectContext(ctx.cwd);
	const projectBlock = sections.length
		? formatProjectContextBlock(projectDir, sections)
		: "";
	return `${systemPrompt}\n\n${formatIntegrationInstructions(projectBlock)}${formatStartupContextBlock()}\n`;
}

// Read local/sessions/startup-context.md and inject it into the system prompt if present.
// Generated by scripts/update-startup-context.sh (the SURFACE step of the self-improving
// loop). Silent no-op when the file is absent — for repos / users that haven't enabled
// the loop yet. Pi's "push surface" for live findings.
function formatStartupContextBlock(): string {
	const path = join(BRAIN_DIR, "local", "sessions", "startup-context.md");
	if (!existsSync(path)) return "";
	try {
		const content = readFileSync(path, "utf8").trim();
		if (!content) return "";
		return `\n\n${content}`;
	} catch {
		return "";
	}
}

function formatProjectContextBlock(
	projectDir: string | undefined,
	sections: string[],
): string {
	return `\n\n## Detected agentBrain Project Context\n\nProject folder: ${projectDir ? relativeToBrain(projectDir) : "(unknown)"}\n\n${sections.join("\n\n---\n\n")}`;
}

function formatIntegrationInstructions(projectBlock: string): string {
	return `## agentBrain Integration\n\nagentBrain is the user's canonical persistent memory at ${BRAIN_DIR}. Use the agentbrain_* tools for memory lookup before falling back to ad-hoc shell searches. At the start of meaningful coding work, consult the core memory files: ${CORE_FILES.join(", ")}, and your preferences under local/preferences/personal/ (each carries a "Wanneer" section that says when it applies). Save reusable learnings and reproducible fixes back to agentBrain according to system/rules.md. Never store secrets in shared notes. When writing a note under local/: use \`bash ${BRAIN_DIR}/scripts/new-note.sh <type> <vault-rel-path-no-ext> [title]\` for correct frontmatter — NEVER type the id field by hand (uuid5-gen.sh parity is enforced by the note-id-validator extension).${projectBlock}`;
}
