#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# fixture-brain.sh — what every fixture brain needs, said once.
#
# A test that builds a throwaway brain has to get two things right, and each
# test used to get them right by hand:
#
#   1. It owns its brain location. setup.sh exports VAULT to its children, a
#      shell may export AGENTBRAIN_DIR, an installer AGENTBRAIN_VAULT. A fixture
#      test that inherits any of them looks at the caller's brain instead of its
#      own, and fails only under setup, the installer, or that shell.
#   2. It carries the libraries the scripts it copies will source. A test that
#      copies new-note.sh and picks its dependencies by name is correct until
#      the script gains one: scripts/lib/vault.sh arrived, and every hand-picked
#      list was one file short. scripts/lib/ is copied whole, so the next
#      library costs no test anything.
#
# Usage:  source "$ROOT/scripts/lib/fixture-brain.sh"
#         clear_brain_env                  # a test that only runs scripts in place
#         fixture_brain "$FIXTURE" "$ROOT" # a test that copies scripts into a brain

# The same names the doctor strips per check (scripts/checks/doctor.sh).
clear_brain_env() {
	unset VAULT AGENTBRAIN_DIR AGENTBRAIN_VAULT AGENTBRAIN_VAULT_DIR \
		AGENTBRAIN_LOCAL_DIR BRAIN_DIR BRAIN_ALIAS
}

# fixture_brain <fixture-root> <checkout-root>
# The layout setup makes (vault/ the directory, local/ the alias), the shared
# libraries, and a brain.json with a fixed namespace: the machine's own
# brain.json is generated by setup and absent from a bare checkout or a linked
# worktree, and a fixture has no reason to depend on it.
fixture_brain() {
	local fixture="${1:?fixture_brain needs the fixture root}"
	local src="${2:?fixture_brain needs the checkout root}"
	clear_brain_env
	mkdir -p "$fixture/vault" "$fixture/scripts/lib" || return 1
	ln -sfn vault "$fixture/local" || return 1
	cp -R "$src/scripts/lib/." "$fixture/scripts/lib/" || return 1
	[ -f "$fixture/brain.json" ] ||
		printf '{"namespace":"a3b2c1d0-1234-5678-9abc-def012345678"}\n' >"$fixture/brain.json"
}
