#!/usr/bin/env bash
# Type-check Pi extension sources with a reproducible TypeScript compiler.
# The extension tsconfig is generated by scripts/configure-pi.sh because it points
# at the locally installed Pi package/type paths. CI may not have that generated
# file, so this check skips unless the local Pi extension tsconfig exists.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXT_DIR="$ROOT_DIR/system/pi-config/extensions"
TSCONFIG="$EXT_DIR/tsconfig.json"

if [ ! -f "$TSCONFIG" ]; then
	echo "Pi extension type-check skipped: $TSCONFIG not found. Run scripts/configure-pi.sh to generate it."
	exit 0
fi

cd "$EXT_DIR"
npm exec --yes --package typescript -- tsc -p tsconfig.json --noEmit

# Also type-check test files using their own tsconfig (which adds @types/node)
TEST_TSCONFIG="$EXT_DIR/tests/tsconfig.json"
if [ ! -f "$TEST_TSCONFIG" ]; then
	echo "Pi extension type-check FAILED: tests/tsconfig.json is missing." >&2
	echo "Test files need their own tsconfig to enable @types/node for the LSP." >&2
	echo "Create system/pi-config/extensions/tests/tsconfig.json with \"types\": [\"node\"]." >&2
	exit 1
fi
npm exec --yes --package typescript -- tsc -p tests/tsconfig.json --noEmit

echo "Pi extension type-check passed."
