#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Type-check Pi extension sources with a reproducible TypeScript compiler.
# The extension tsconfig is generated by scripts/configure-pi.sh because it points
# at the locally installed Pi package/type paths. CI may not have that generated
# file, so this check skips unless the local Pi extension tsconfig exists.

set -euo pipefail

# npm lives in nvm-managed Node — load user tool paths before probing.
# shellcheck disable=SC1091
TOOLPATHS_DIR="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/../lib" && pwd)"
# shellcheck disable=SC1091
. "$TOOLPATHS_DIR/_toolpaths.sh"

ROOT_DIR="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/../.." && pwd)"
EXT_DIR="$ROOT_DIR/system/pi-config/extensions"
TSCONFIG="$EXT_DIR/tsconfig.json"

if [ ! -f "$TSCONFIG" ]; then
	echo "Pi extension type-check skipped: $TSCONFIG not found. Run scripts/configure-pi.sh to generate it."
	exit 0
fi

cd "$EXT_DIR"
npm exec --yes --package typescript -- tsc -p tsconfig.json --noEmit

# Also type-check test files using their own tsconfig (which adds @types/node)
TEST_TSCONFIG="$EXT_DIR/tests/tsconfig.json"
if [ ! -f "$TEST_TSCONFIG" ]; then
	echo "Pi extension type-check FAILED: tests/tsconfig.json is missing." >&2
	echo "Test files need their own tsconfig to enable @types/node for the LSP." >&2
	echo "Create system/pi-config/extensions/tests/tsconfig.json with \"types\": [\"node\"]." >&2
	exit 1
fi
npm exec --yes --package typescript -- tsc -p tests/tsconfig.json --noEmit

echo "Pi extension type-check passed."

# Imports stay inside extensions/. configure-pi links every entry of that
# directory into ~/.pi/agent/extensions, one link per entry, and Pi resolves a
# relative import from the link's path: "../../addons/goal/lib/core" then points
# into ~/.pi and the extension fails to load (a second machine, 2026-09-07).
# A lib that lives elsewhere is reached through a link inside extensions/.
_outside="$(grep -nE 'from "\.\./' "$ROOT_DIR"/system/pi-config/extensions/*.ts 2>/dev/null || true)"
if [ -n "$_outside" ]; then
	echo "FAIL extension imports outside extensions/ (link the lib in, like goal-lib):" >&2
	printf '%s\n' "$_outside" | sed 's/^/  /' >&2
	exit 1
fi
